const mongoose = require('mongoose');

/**
 * StrategicPrioritiesAnalysis Schema
 * Stores industry-level analysis of strategic priorities across all banks
 * Generated by the Strategic Priorities Agent via batch processing
 */
const strategicPrioritiesAnalysisSchema = new mongoose.Schema({
  // Analysis metadata
  analysisDate: {
    type: Date,
    required: true,
    default: Date.now
  },

  // Coverage statistics
  coverage: {
    totalBanks: {
      type: Number,
      required: true
    },
    banksWithPriorities: {
      type: Number,
      required: true
    },
    banksWithFocusMetrics: {
      type: Number,
      default: 0
    },
    banksWithTechPartnerships: {
      type: Number,
      default: 0
    },
    totalPrioritiesAnalyzed: {
      type: Number,
      required: true
    },
    averagePrioritiesPerBank: {
      type: Number
    },
    // Asset coverage (what % of industry assets are represented)
    totalAssetsRepresented: {
      type: Number // In thousands
    },
    assetCoveragePercent: {
      type: Number
    }
  },

  // Categorized priorities - grouped by theme
  categories: [{
    name: {
      type: String,
      required: true
    },
    description: {
      type: String
    },
    // How many banks mention priorities in this category
    bankCount: {
      type: Number,
      required: true
    },
    // Percentage of analyzed banks with this priority
    prevalence: {
      type: Number // 0-100
    },
    // Individual priorities within this category
    priorities: [{
      title: {
        type: String,
        required: true
      },
      normalizedTitle: {
        type: String // Cleaned up version for matching
      },
      description: {
        type: String
      },
      // Banks that have this specific priority
      banks: [{
        idrssd: String,
        bankName: String,
        totalAssets: Number, // In thousands
        originalTitle: String, // Bank's exact wording
        originalDescription: String,
        citations: [{
          documentTitle: String,
          citedText: String,
          pageNumber: Number
        }]
      }],
      bankCount: {
        type: Number
      }
    }],
    // Key themes or common language used
    commonLanguage: [{
      type: String
    }]
  }],

  // Industry-level insights summary
  industrySummary: {
    // Top strategic themes across all banks (ranked by prevalence)
    topThemes: [{
      theme: String,
      description: String,
      bankCount: Number,
      prevalence: Number, // Percentage
      exampleBanks: [String] // Bank names
    }],
    // Key observations about industry direction
    keyObservations: [{
      observation: String,
      supportingEvidence: String
    }],
    // Emerging trends (mentioned by smaller number of banks, but notable)
    emergingTrends: [{
      trend: String,
      description: String,
      bankCount: Number,
      banks: [String]
    }]
  },

  // Differentiating strategies - unique to one or few banks
  differentiatingStrategies: [{
    title: {
      type: String,
      required: true
    },
    description: {
      type: String
    },
    // Why this is considered differentiating
    uniquenessReason: {
      type: String
    },
    // Banks with this strategy
    banks: [{
      idrssd: String,
      bankName: String,
      totalAssets: Number,
      originalTitle: String,
      originalDescription: String,
      citations: [{
        documentTitle: String,
        citedText: String,
        pageNumber: Number
      }]
    }],
    bankCount: {
      type: Number
    },
    // Categorization
    category: {
      type: String // e.g., "Technology", "Market Focus", "Product Innovation"
    }
  }],

  // Focus Metrics Analysis (what KPIs banks are focused on)
  focusMetricsAnalysis: {
    // Most commonly tracked metrics across banks
    topMetrics: [{
      metric: String,
      bankCount: Number,
      prevalence: Number,
      banks: [{
        idrssd: String,
        bankName: String,
        commentary: String
      }]
    }],
    // Unique metrics only tracked by few banks
    uniqueMetrics: [{
      metric: String,
      banks: [{
        idrssd: String,
        bankName: String,
        commentary: String
      }]
    }]
  },

  // Technology partnerships analysis
  techPartnershipsAnalysis: {
    // Most common technology partners
    topPartners: [{
      partner: String,
      bankCount: Number,
      banks: [{
        idrssd: String,
        bankName: String,
        description: String
      }]
    }],
    // Technology focus areas
    focusAreas: [{
      area: String,
      bankCount: Number,
      examples: [String]
    }]
  },

  // Raw data used for analysis (for debugging/transparency)
  rawData: {
    banksAnalyzed: [{
      idrssd: String,
      bankName: String,
      totalAssets: Number,
      priorityCount: Number
    }]
  },

  // Analysis metadata
  analysisMetadata: {
    model: {
      type: String // Claude model used
    },
    processingTime: {
      type: Number // Seconds
    },
    version: {
      type: String,
      default: '1.0'
    }
  }

}, {
  timestamps: true
});

// Index for querying latest analysis
strategicPrioritiesAnalysisSchema.index({ analysisDate: -1 });

// Static method to get the latest analysis
strategicPrioritiesAnalysisSchema.statics.getLatest = async function() {
  return this.findOne().sort({ analysisDate: -1 });
};

// Static method to get analysis history
strategicPrioritiesAnalysisSchema.statics.getHistory = async function(limit = 10) {
  return this.find()
    .sort({ analysisDate: -1 })
    .limit(limit)
    .select('analysisDate coverage.totalBanks coverage.banksWithPriorities analysisMetadata');
};

module.exports = mongoose.model('StrategicPrioritiesAnalysis', strategicPrioritiesAnalysisSchema);
